### ISSUE TITLE
[FEATURE REQUEST] support obsidian 1.0 new tab behavior 

### ISSUE THREAD

**Issue by Ravenclawer** [chhoumann/quickadd#290]
**Is your feature request related to a problem? Please describe.**
 when open new tab option 
![image](https://user-images.githubusercontent.com/73892411/195784453-469249ef-ae6b-4898-8687-0c98a026a100.png)
the new note will be opened in a separate pane instead of new tab in the obsidan 1.0 version which causes clutter of the obsidian interface.

**Describe the solution you'd like**
open new note created by quickadd plugin in new tab instead of new pane 
**Additional context**

**Comment by JoarDev** [comment]
It would be great if the "new tab" option actually opened a new tab instead of a new pane

**Comment by Superfeuchter** [comment]
Yes! New tab instead of new pane - this would be great!

**Comment by chhoumann** [comment]
Added this in the latest update. 

The previous option fit the pre-1.0 Obsidian semantics, but didn't make sense after.

More customizability of where to open (e.g. new window) is coming in a future update.

**Comment by seomwan** [comment]
Is this working as intended? When I have it set to open in the current tab, it doesn't work (i.e. not in a new tab).
I'd prefer it to work that way as new tabs introduce clutter, especially on mobile where it's harder to close many tabs at once.

This is a regression from earlier when the previous version (0.5.x) worked with Obsidian 1.0+ tabs (or the version which introduced tabs).

**Comment by Superfeuchter** [comment]
Now I updated the plugin and turned off "new split" in options in my templates, and now it works as expected. The new note opens in a new tab, not in a new pane. Thumbs up! Thank you.

**Comment by Ravenclawer** [comment]
I still get new pane when I expected a new TAB , where can I get this new split option？

**Comment by Ravenclawer** [comment]
this feature request is not addressed

**Comment by Ravenclawer** [comment]
the old command cannot be automatically update to the new setting

**Comment by Ravenclawer** [comment]
the capture option still don't support capure to new tab option and still opened a new pane for the captured content

**Comment by Superfeuchter** [comment]
try to turn off "new split" in template-options
