### ISSUE TITLE
Unable to detect Object type

### ISSUE THREAD

**Issue by DhananjayPorwal** [chhoumann/quickadd#418]
I was using this app from Jan 2023 and It helps me a lot. Currently my `add movie` macro won't work. I traced the issue and found it was because of `file name`, I set the value to `{{VALUE:fileName}}` which was working fine till date. Currently, it just shows `_field_`. 
![image](https://user-images.githubusercontent.com/51775507/224008520-b35925ae-b3a6-4817-84f5-93af8ebad733.png)

**Comment by chhoumann** [comment]
Hi @DhananjayPorwal 

Thanks for reporting this!
I've just pushed an update which ensures the correct file name is shown.

I'm not sure if this quite fixed the issue. Can you confirm?
If it didn't, please provide e.g. a screenshot of / the text in the console, so I can debug better.

**Comment by DhananjayPorwal** [comment]
Yes, you fixed the issue, but still its functionality is still missing.

Steps to recreate:

1. Create a movie template.
2. Go to Quick Add and create a macro named `lookup movie`.
3. Now Configure the Macro.
4. Add `movie.js` to the macro in user script.
5. Now click on gear icon which is just created and put OMDB API there.
6. Now Click on template and select the movie template which you just created in the step (1).
7. Now click on the gear icon of that template to configure it.
8. In the Template path section, locate the path of template and enable the File Name Format toggle.
9. Enter `{{VALUE:fileName}}`in File Name section.
10. Now come to the `QuickAdd` setting and create a macro name Add Movie and Click Add Choice.
11. Now Open Command Palette and search `add movie`.
12. Select it and search any movie.
13. If it behaves normally, it should show related movies but currently it is not showing anything.

References: 
OMDB API Key: https://www.omdbapi.com/apikey.aspx
movies.js: [Your own script 😁](https://github.com/chhoumann/quickadd/blob/master/docs/docs/Examples/Attachments/movies.js)
Movie Template: 

poster: {{VALUE:Poster}}
imdbId: {{VALUE:imdbID}}
scoreImdb: {{VALUE:imdbRating}}
length: {{VALUE:Runtime}}
genre: {{VALUE:Genre}}
year: {{VALUE:Year}}
cast: {{VALUE:Actors}}
director: {{VALUE:Director}}
rating:
status:

YouTube Video: https://www.youtube.com/watch?v=t-hKCgGhQuk&t=270s


Current Behavior:


https://user-images.githubusercontent.com/51775507/224099385-84737cdf-8a34-4a8b-8310-92d67dd2fc37.mp4

**Comment by chhoumann** [comment]
Thanks for the details! It really helps.

But very odd that nothing appears at all.
Are you getting any errors in the console? (cmd+ option + i on Mac I think and ctrl + shift + i for Windows).
Anything at all related to QuickAdd?

I'm seeing the usual behavior when I use the `movies` script, hence my wondering.

**Comment by DhananjayPorwal** [comment]
When I opened the `Console` it seems to be fine.

![image](https://user-images.githubusercontent.com/51775507/224276929-df1cfd75-6c70-4d27-af8f-8eb2f24a5f10.png)

After that, when I fire the `Add Movie` macro through `Command Palette` it give me this error.

![image](https://user-images.githubusercontent.com/51775507/224277186-6e2a776a-0e5b-4e94-9bac-2f42a407fec4.png)

When I click on the last link of the error, It shows me this:

![image](https://user-images.githubusercontent.com/51775507/224277338-62a8d080-3434-49e1-9e69-ababd52ffc6e.png)

Should I share the app.js file with you?

**Comment by chhoumann** [comment]
Thanks for the screenshots!

No need to share the `app.js` file. You're getting a 401 Unauthorized error, which means there's something up with your API key / access to OMDB. Can you try generating a new API key and using that?

**Comment by DhananjayPorwal** [comment]
Thanks @chhoumann 🎉🎊
It was the API's issue. Regenerating API fixed the issue. 😁

**Comment by chhoumann** [comment]
Glad to hear we got it resolved!
